export const LISTINGS_LOADING = 'LISTINGS_LOADING';
export const ADD_LISTINGS = 'ADD_LISTINGS';
export const LISTINGS_FAILED = 'LISTINGS_FAILED';
export const CREATE_LISTING = 'CREATE_LISTING';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS FAILED';
